# Generated by Django 3.0.8 on 2020-07-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['id']},
        ),
    ]
